# UGVCalibrate.action

# goal definition
# this section defines the input parameters required to complete the action.

int64 num_measurements

---

# result definition
# this section defines the output parameters after executing the goal.

bool success
geometry_msgs/Quaternion quat_diff

---

# feedback definition
# this section provides feedback during the execution of the goal.

float64 progress